### ISSUE TITLE
Using docker behind reverse-proxy

### ISSUE THREAD

**Issue by loranger** [Sorunome/mx-puppet-slack#129]
Hello,

I try to make this slack bridge work using docker and traefik reverse-proxy, but it seems at startup, the bindAddress is resolved as an ip. Then the reverse proxy rules are ignored and the bridge cannot recieved and call

Here is the beginning of my `config.yaml` file:

```yaml
bridge:
  # Port to host the bridge on
  # Used for communication between the homeserver and the bridge
  port: 443
  # The host connections to the bridge's webserver are allowed from
  bindAddress: slack.matrix.my.tld
  # Public domain of the homeserver
  domain: matrix.my.tld
  # Reachable URL of the Matrix homeserver
  homeserverUrl: https://matrix.my.tld
```

The bridge and the synapse have their own hostname and uses a letsencrypt certificate.
On docker-compose up, the bridge cannot bind its listen address (I replaced my real public ip with 01.02.03.04)

```
(...)
matrix-slack-bridge | Sep-19 16:37:11.592 [Store] info: Database schema version is 1, latest version is 1
matrix-slack-bridge | Sep-19 16:37:11.593 [PuppetBridge] info: Starting application service....
matrix-slack-bridge | node:events:304
matrix-slack-bridge |       throw er; // Unhandled 'error' event
matrix-slack-bridge |       ^
matrix-slack-bridge |
matrix-slack-bridge | Error: listen EADDRNOTAVAIL: address not available 01.02.03.04:443
matrix-slack-bridge |     at Server.setupListenHandle [as _listen2] (node:net:1269:21)
matrix-slack-bridge |     at listenInCluster (node:net:1334:12)
matrix-slack-bridge |     at GetAddrInfoReqWrap.doListen [as callback] (node:net:1471:7)
matrix-slack-bridge |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:69:8)
matrix-slack-bridge | Emitted 'error' event on Server instance at:
matrix-slack-bridge |     at emitErrorNT (node:net:1313:8)
matrix-slack-bridge |     at processTicksAndRejections (node:internal/process/task_queues:80:21) {
matrix-slack-bridge |   code: 'EADDRNOTAVAIL',
matrix-slack-bridge |   errno: -99,
matrix-slack-bridge |   syscall: 'listen',
matrix-slack-bridge |   address: '01.02.03.04',
matrix-slack-bridge |   port: 443
matrix-slack-bridge | }
matrix-slack-bridge exited with code 1
```

How can I use mx-puppet-slack using docker behind my reverse-proxy ?
