### ISSUE TITLE
Ability to append suffix to bridged person name

### ISSUE THREAD

**Issue by matejdro** [Sorunome/mx-puppet-slack#43]
Currently bridge bridges all users with their full name. However, if I have people with same names added via different bridges, it can become confusing on which person comes from which bridge.

It would be really great if this bridge had an option to add `(Slack)` suffix to name of every bridged contact, or even better, append name of the workspace (that way there are also no clashes between same people in different workspaces).

**Comment by Sorunome** [comment]
Time to introduce you to name patterns!

You can add this little config block to your config.yaml

```
namePatterns:
  # Override the protocols set default name patterns
  # Which variables are available depends on protocol implementation
  user: :name
  userOverride: :name
  room: :name
  group: :name
```

These define patterns for users, userOverrides (slack doesn't use those), rooms (channels) and groups (teams) respectively. By default for slack they look like

```
namePatterns:
  user: :name
  room: :name - :team
  group: :name
```

As you can see, you can define variables with `:var`. Available variables are "name" and "team"

So, to prepend the team name also to users you could do

```
namePatterns:
  user: :name - :team
  room: :name - :team
  group: :name
```

Or do that AND prepend `(Slack)` just do
```
namePatterns:
  user: :name - :team (Slack)
  room: :name - :team (Slack)
  group: :name (Slack)
```

Hope that helps!
