### ISSUE TITLE
titles for newly created rooms are ignoring NamePatterns

### ISSUE THREAD

**Issue by ericmigi** [Sorunome/mx-puppet-slack#50]
![Screenshot-20200407203113-542x61](https://user-images.githubusercontent.com/1048265/78820446-aba01980-798c-11ea-8fb0-7dd3a0f58a0a.png)

```
namePatterns:
  user: :name [:team? - :team,]  Slack
  room: :name [:team? - :team,]  Slack
  group: :name - Slack
```
